<a href="https://colab.research.google.com/github/ISPC-PROYECTOS/CienciaDatosABP/blob/main/Data_Science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importamos el dataset de Kaggle, buscamos el archivo CSV

In [1]:
import kagglehub
import os

path = kagglehub.dataset_download("lucalullo/global-ghg-gas-emissions-by-country-1950-2024")
print("Ruta del dataset:", path)

archivos = os.listdir(path)
print("Archivos descargados:", archivos)

Downloading to /root/.cache/kagglehub/datasets/lucalullo/global-ghg-gas-emissions-by-country-1950-2024/1.archive...

100%|██████████| 299k/299k [00:00<00:00, 891kB/s]

Extracting files...
Ruta del dataset: /root/.cache/kagglehub/datasets/lucalullo/global-ghg-gas-emissions-by-country-1950-2024/versions/1
Archivos descargados: ['emissioni-gas-serra-globali-per-paese-1950-2024.csv']

Buscamos el primer archivo que termine en .csv y unimos la ruta de la carpeta con el nombre del archivo. Luego lo cargamos en pandas y verificamos que se haya cargado.

In [2]:
import pandas as pd

# Buscamos el primer archivo que termine en '.csv'
nombre_csv = [archivo for archivo in archivos if archivo.endswith('.csv')][0]

# Unimos la ruta de la carpeta con el nombre del archivo
ruta_completa = os.path.join(path, nombre_csv)

# Lo cargamos en pandas
df = pd.read_csv(ruta_completa)

# Vemos las primeras 5 filas para confirmar que todo salió bien
df.head()

       country  year iso_code  total_ghg  ghg_per_capita
0  Afghanistan  1950      AFG  19.868742        2.555078
1  Afghanistan  1951      AFG  21.069101        2.673967
2  Afghanistan  1952      AFG  22.094320        2.766014
3  Afghanistan  1953      AFG  23.255630        2.872235
4  Afghanistan  1954      AFG  24.250988        2.954572

# Primer análisis del dataset
Este conjunto de datos contiene las emisiones de gases de efecto invernadero a nivel nacional desde 1950 hasta 2024.

El conjunto de datos se deriva del conjunto de datos de emisiones de CO₂ y gases de efecto invernadero publicado por Our World in Data, que integra varias fuentes científicas ampliamente utilizadas en la investigación climática.

Cada observación representa un registro de un país y un año, y abarca 199 países de todo el mundo.

Incluye información sobre:
- Emisiones totales de gases de efecto invernadero
- Emisiones de gases de efecto invernadero per cápita

**Variables**

- Country → nombre del país
- Year → año de observación
- Iso_code → Código de país ISO
- Total_ghg → emisiones totales de gases de efecto invernadero expresadas en millones de toneladas de CO₂ equivalente
- Ghg_per_capita → emisiones de gases de efecto invernadero por persona, expresadas en toneladas de CO₂ equivalente per cápita.

El dataset posee un total de 14.925 registros

Fuentes:
- Dataset “Global GHG gas emissions by country (1950–2024)” publicado por Luca Lullo en Kaggle.
- Datos originales derivados de Our World in Data, que integran:
   • Global Carbon Project – Global Carbon Budget
   • PRIMAP-hist greenhouse gas emissions database
   • United Nations World Population Prospects
   • Gapminder population series

# **Análisis de Datos Inicial**
Vamos a explorar el df para entender su estructura, identificar valores nulos, duplicados y obtener estadísticas descriptivas.

In [3]:
# 1. Información general del DataFrame y tipos de datos
print('Información general del DataFrame:')
df.info()

# 2. Conteo de valores nulos por columna
print('\nConteo de valores nulos por columna:')
display(df.isnull().sum())

Información general del DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14925 entries, 0 to 14924
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   country         14925 non-null  object
 1   year            14925 non-null  int64
 2   iso_code        14925 non-null  object
 3   total_ghg       14475 non-null  float64
 4   ghg_per_capita  14475 non-null  float64
dtypes: float64(2), int64(1), object(2)
memory usage: 583.1+ KB

Conteo de valores nulos por columna:

country             0
year                0
iso_code            0
total_ghg         450
ghg_per_capita    450
dtype: int64

In [7]:
# 3. Conteo de filas duplicadas
num_duplicados = df.duplicated().sum()
print(f'Número de filas duplicadas: {num_duplicados}')

if num_duplicados > 0:
    print('\nEjemplo de filas duplicadas:')
    display(df[df.duplicated(keep=False)].sort_values(by=df.columns.tolist()).head()) # Muestra algunas filas duplicadas

Número de filas duplicadas: 0

In [5]:
# 4. Parámetros estadísticos descriptivos para columnas numéricas
print('\nParámetros estadísticos descriptivos:')
display(df.describe())

Parámetros estadísticos descriptivos:

               year     total_ghg  ghg_per_capita
count  14925.000000  14475.000000    14475.000000
mean    1987.000000    188.028820        9.259861
std       21.649436    706.305423       12.160517
min     1950.000000     -9.218572       -5.197811
25%     1968.000000      7.289340        2.858160
50%     1987.000000     34.407463        5.909035
75%     2006.000000     99.218967       11.049553
max     2024.000000  14107.006836      369.705292

In [6]:
# 5. Parámetros estadísticos descriptivos para columnas categóricas (objetos)
print('\nParámetros estadísticos descriptivos para columnas categóricas:')
display(df.describe(include='object'))

Parámetros estadísticos descriptivos para columnas categóricas:

            country iso_code
count         14925    14925
unique          199      199
top     Afghanistan      AFG
freq             75       75